#!/bin/sh
# for hints see https://forum.ffrn.de/t/workaround-841n-load-neustart-problem/1167/39
# and similar https://github.com/Freifunk-Rhein-Neckar/ffrn-packages/ffrn-lowmem-patch
mem=$(cat /proc/meminfo |grep MemTotal |grep -oE [0-9]*)

# check if config mode is done before
conf=$(uci get gluon-setup-mode.@setup_mode[0].configured)
if [ $conf -ne 1 ] ; then logger "$0 : router seems to be unconfigured, if in configmode enable haveged and exit"; fi

# start haveged in config mode
MODE=`uci get gluon-setup-mode.@setup_mode[0].enabled`
if [ $MODE == "1" ] ; then
	/etc/init.d/haveged start
	exit 0
fi

# check memory available
if [ $mem -le 35000 ] ; then
	# disable and stop haveged if enabled
	if [ -f /etc/rc.d/S13haveged ] ; then    
	        /etc/init.d/haveged disable
        	/etc/init.d/haveged stop
	fi
	# incl. defaults
	sysctl -w net.ipv6.neigh.default.gc_interval=60 	# 30
	sysctl -w net.ipv6.neigh.default.gc_stale_time=120	# 60
	sysctl -w net.ipv6.neigh.default.gc_thresh1=64		# 128
	sysctl -w net.ipv6.neigh.default.gc_thresh2=128		# 256
	sysctl -w net.ipv6.neigh.default.gc_thresh3=512		# 1024
        sysctl -w net.ipv4.neigh.default.gc_interval=60		# 30
        sysctl -w net.ipv4.neigh.default.gc_stale_time=120	# 60
        sysctl -w net.ipv4.neigh.default.gc_thresh1=64		# 128
        sysctl -w net.ipv4.neigh.default.gc_thresh2=128		# 256
        sysctl -w net.ipv4.neigh.default.gc_thresh3=512		# 1024
        sysctl -w vm.min_free_kbytes=1024			# 670
        sysctl -w vm.dirty_background_ratio=5			# 10
        sysctl -w vm.dirty_ratio=30				# 20
        sysctl -w vm.dirty_expire_centisecs=0			# 3000
fi

logger "$0 succesfully"

exit 0
